manifest:
  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk
      revision: feat/pointers-move-scroll
      import: app/west.yml

    - name: zmk-pmw3610-driver
      url: https://github.com/inorichi/zmk-pmw3610-driver
      revision: main
